from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

db = SQLAlchemy()


class Deployment(db.Model):
    id = ...
    build_number = ...
    version = ...
    status = ...
    deployed_at = ...
